- name: Create ibmtpm directory
  file:
    path: /root/ibmtpm
    state: directory

- name: Download and unarchive ibmtpm
  unarchive:
    src: http://sourceforge.net/projects/ibmswtpm2/files/ibmtpm1119.tar.gz
    dest: /root/ibmtpm
    remote_src: yes

- name: remove -Werror compile flag
  command: sed -i 's/-Werror//g' /root/ibmtpm/src/makefile /root/ibmtpm/src/makefile11

- name: Compile tpm emulator
  make:
      chdir: /root/ibmtpm/src/

- name: Install tpm_server
  command: install -c /root/ibmtpm/src/tpm_server /usr/local/bin/tpm_server

- name: Install init_tpm_server script
  command: install -c /root/keylime/scripts/init_tpm_server /usr/local/bin/init_tpm_server

- name: Install tpm_serverd script
#  command: install -c /root/keylime/scripts/tpm_serverd /usr/local/bin/tpm_serverd
  copy:
    src: files/tpm_serverd
    dest: /usr/local/bin/tpm_serverd
    owner: root
    group: root
    mode: '0755'

#- name: Changing perm of "tpm_serverd", adding "+x"
#  file: dest=/usr/local/bin/tpm_serverd mode=a+x

- name: Changing perm of "init_tpm_server", adding "+x"
  file: dest=/usr/local/bin/init_tpm_server mode=a+x

- name: 'Set environment'
  shell: "echo $TPM2TOOLS_TCTI"
  environment:
    TPM2TOOLS_TCTI: "tabrmd:bus_name=com.intel.tss2.Tabrmd"

- name: Ensure tpm_server is not running
  command: bash -c 'pgrep tpm_server && pkill tpm_server || true'

- name: Start TPM Emulator
  command: /usr/local/bin/tpm_serverd
  become: yes
#  debugger: always

- name: Enable tpm2_abrmd service and ensure it is not masked
  systemd:
    name: tpm2-abrmd
    enabled: yes
    masked: no

- name: Change TCTI to emulator in tpm2-abrmd unit
  copy:
    src: files/tpm2-abrmd.service
    dest: /etc/systemd/system/tpm2-abrmd.service
    owner: root
    group: root
    mode: '0644'

- name: Reload / restart service tpm2-abrmd, in all cases
  systemd:
    name: tpm2-abrmd
    state: restarted
    daemon_reload: yes

